### ISSUE TITLE
Infinite repetition of commands

### ISSUE THREAD

**Issue by odisei369** [libthinkpad/dockd#14]
When I run command 
`dockd --set docked` or `dockd --set undocked` 
It did what it should do, but I get infinite loop of messages: 
`config applied from /etc/dockd/undocked.conf`

Same think with commands `dockd --config docked` and `dockd --config undocked`
It worked, but again I get infinite loop of messages:
`config file written to /etc/dockd/undocked.conf`

My laptop is T430.
dockd was installed from AUR.
Windows manager: i3-gaps.

**Comment by smclt30p** [comment]
See issue #9.

On 11 Sep 2018, at 23:27, Ilya Piatrenka <notifications@github.com<mailto:notifications@github.com>> wrote:


When I run command
dockd --set docked or dockd --set undocked
It did what it should do, but I get infinite loop of messages:
config applied from /etc/dockd/undocked.conf

Same think with commands dockd --config docked and dockd --config undocked
It worked, but again I get infinite loop of messages:
config file written to /etc/dockd/undocked.conf

My laptop is T430.
dockd was installed from AUR.
Windows manager: i3-gaps.

**Comment by odisei369** [comment]
Ok, thanks. Didn't noticed that issue in the first place.
