### ISSUE TITLE
Build AUR without systemd

### ISSUE THREAD

**Issue by LeducH** [libthinkpad/dockd#16]
I manged to install `libthinkpad` without systemd dependency. how can I install dockd without systemd

**Comment by XenGi** [comment]
AFAIK `dockd` doesn't need systemd. I wish the AUR package would ship a service unit so I can use it as a systemd unit but it doesn't.

**Comment by schoettl** [comment]
@LeducH why do you say it depends on systemd?

It shouldn't be too hard to add such a service unit file ;) Do you want to contribute @XenGi ? I'm unsure if it should be a `--user` service or system. I'd start with user, not system for security reasons.

**Comment by schoettl** [comment]
Closing this issue. AFAIK dockd doesn't depend on systemd. I cannot find "systemd" anywhere except in the README (which is also fixed now).
