### ISSUE TITLE
Not working with T480s and USB-C dock

### ISSUE THREAD

**Issue by pkoryzna** [libthinkpad/dockd#17]
Seems like dockd doesn't detect plugging in/out with my T480s and Lenovo USB-C dock.
I am running Xubuntu 18.04 LTS (Bionic) with XFCE (window manager replaced by i3, if that's relevant)

Manually running `dockd --set docked` *does* restore saved monitor layout.

Here's output from `acpi_listen`:
```
$ acpi_listen
UNDOCKING


battery PNP0C0A:00 00000080 00000001
ibm/hotkey LEN0268:00 00000080 00004011
ac_adapter ACPI0003:00 00000080 00000000
ibm/hotkey LEN0268:00 00000080 00006030
thermal_zone LNXTHERM:00 00000081 00000000



DOCKING 


ibm/hotkey LEN0268:00 00000080 00004011
battery PNP0C0A:00 00000080 00000001
ac_adapter ACPI0003:00 00000080 00000001
ibm/hotkey LEN0268:00 00000080 00006030
thermal_zone LNXTHERM:00 00000081 00000000
^C
```

Kernel version
`Linux koryzna-ThinkPad-T480s 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
Docked lsusb output:
```
Bus 002 Device 045: ID 17ef:1020 Lenovo 
Bus 002 Device 044: ID 17ef:3062 Lenovo 
Bus 002 Device 043: ID 17ef:101f Lenovo 
Bus 002 Device 039: ID 0bda:0316 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04f2:b604 Chicony Electronics Co., Ltd 
Bus 001 Device 053: ID 8087:0a2b Intel Corp. 
Bus 001 Device 081: ID 17ef:3063 Lenovo 
Bus 001 Device 080: ID 047d:1020 Kensington Expert Mouse Trackball
Bus 001 Device 079: ID 29ea:0102  
Bus 001 Device 078: ID 17ef:1021 Lenovo 
Bus 001 Device 077: ID 17ef:1026 Lenovo 
Bus 001 Device 076: ID 17ef:3060 Lenovo 
Bus 001 Device 075: ID 17ef:1025 Lenovo 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by pkoryzna** [comment]
I did run the acpi_listen again and it seems to be a problem with ACPI reporting only **undocked** events: `ibm/hotkey LEN0268:00 00000080 00004011` - not sure if this is a bug in BIOS, dock firmware or kernel. 

Don't have a Windows partition anymore to update the dock.

**Comment by maltere** [comment]
Same Problem with T480s and the Lenovo Thunderbolt 3 Dock using Arch 4.20.3-arch1-1-ARCH

The command `dockd --config docked` leads to following output and the comand is not terminating

> config file written to /etc/dockd/docked.conf
> config file written to /etc/dockd/undocked.conf
> config file written to /etc/dockd/undocked.conf
> config file written to /etc/dockd/undocked.conf
> ...
> config file written to /etc/dockd/undocked.conf

same problem when using `dockd --set docked`

Both commands do work, after terminating the commands with cmd+c.
Autodetection with `dockd --deamon` does not work.

**Comment by smclt30p** [comment]
See issue #8.

On 19 Jan 2019, at 11:41, maltere <notifications@github.com<mailto:notifications@github.com>> wrote:


Same Problem with T480s and the Lenovo Thunderbolt 3 Dock using Arch 4.20.3-arch1-1-ARCH

The command dockd --config docked leads to following output and the comand is not terminating

config file written to /etc/dockd/docked.conf
config file written to /etc/dockd/undocked.conf
config file written to /etc/dockd/undocked.conf
config file written to /etc/dockd/undocked.conf
...
config file written to /etc/dockd/undocked.conf

same problem when using dockd --set docked

Both commands do work, after terminating the commands with cmd+c.
Autodetection with dockd --deamon does not work.

**Comment by smclt30p** [comment]
Pardon, issue #9 and check the issue9 branch.

On 19 Jan 2019, at 11:41, maltere <notifications@github.com<mailto:notifications@github.com>> wrote:


Same Problem with T480s and the Lenovo Thunderbolt 3 Dock using Arch 4.20.3-arch1-1-ARCH

The command dockd --config docked leads to following output and the comand is not terminating

config file written to /etc/dockd/docked.conf
config file written to /etc/dockd/undocked.conf
config file written to /etc/dockd/undocked.conf
config file written to /etc/dockd/undocked.conf
...
config file written to /etc/dockd/undocked.conf

same problem when using dockd --set docked

Both commands do work, after terminating the commands with cmd+c.
Autodetection with dockd --deamon does not work.

**Comment by pkoryzna** [comment]
I do not have the computer anymore. Closing the issue
