### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by zelmor** [libthinkpad/dockd#19]
Lenovo legal team strikes again?

**Comment by smclt30p** [comment]
Domain issues, use libthinkpad.github.io<http://libthinkpad.github.io>

On 4 Dec 2018, at 22:15, zelmor <notifications@github.com<mailto:notifications@github.com>> wrote:


Lenovo legal team strikes again?

**Comment by zelmor** [comment]
Thank you. This should be reflected here:
https://github.com/libthinkpad
and here:
https://github.com/libthinkpad/dockd
