### ISSUE TITLE
Readme is full of manual linebreaks

### ISSUE THREAD

**Issue by Wrzlprmft** [libthinkpad/dockd#21]
`README.md` is full of manual linebreaks at random places that are in conflict with automatic linebreaks when GitHub (or anything else renders the text). The result is painful to read.

![image](https://user-images.githubusercontent.com/291070/51542880-9230b180-1e5c-11e9-8493-973ed5df26da.png)

**Comment by XenGi** [comment]
I cleaned up the README and fixed most of the markdown. I did no changes to the content of the document.

**Comment by schoettl** [comment]
Acknowledged, pending PRs, closing this issue.
