### ISSUE TITLE
dockd: error while loading shared libraries: libthinkpad.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by turkus** [libthinkpad/dockd#25]
Hi,

thanks for the package. 
I went through all steps and everything worked fine except the last one:
`dockd`
On this execution it printed:
`dockd: error while loading shared libraries: libthinkpad.so.1: cannot open shared object file: No such file or directory`

Well, I installed everything as they wanted from the source:
https://github.com/libthinkpad/libthinkpad
and also seemed ok.

How to make libthinkpad.so.1 to be visible for dockd?

```
➜  dockd git:(master) ✗ ls -la /usr/lib64/              
total 160
drwxr-xr-x  2 root root   4096 kwi  7 10:42 .
drwxr-xr-x 11 root root   4096 kwi  7 10:16 ..
lrwxrwxrwx  1 root root     16 kwi  7 10:16 libthinkpad.so -> libthinkpad.so.1
lrwxrwxrwx  1 root root     18 kwi  7 10:16 libthinkpad.so.1 -> libthinkpad.so.2.6
-rw-r--r--  1 root root 153336 kwi  7 10:42 libthinkpad.so.2.6
```

I will look forward to get your help guys.

**Comment by turkus** [comment]
Well,

solved by:

`sudo ln -s /usr/lib64/libthinkpad.so.2.6 /usr/lib/libthinkpad.so.1`

Hope that would help someone.

**Comment by isinaltinkaya** [comment]
For me the solution was to use:
`sudo ln -vs /usr/local/lib/libthinkpad.so /lib/libthinkpad.so.1`

**Comment by rileyrg** [comment]
> Well,
> 
> solved by:
> 
> `sudo ln -s /usr/lib64/libthinkpad.so.2.6 /usr/lib/libthinkpad.so.1`
> 
> Hope that would help someone.

It helped me! Thanks!
