### ISSUE TITLE
Auto docking switch doesn't work x250

### ISSUE THREAD

**Issue by baj0k** [libthinkpad/dockd#26]
ThinkPad x250 with 40a1 docking station. After -reconnecting to the dock station I need to configure xrandr again.

    $ journalctl -b | grep dock

kernel: acpi PNP0C0A:01: ACPI dock station (docks/bays count: 1) 
kernel: thinkpad_acpi: docked into hotplug port replicator 
dockd[823]: Error: output from config (DP2-2) not found on this machine 
dockd[823]: Mode lookup error: No such device 
dockd[823]: Controller config is not valid, not committing changes to X 
dockd[823]: Undock hook exited with non-zero (32256)

    $ xrandr

Screen 0: minimum 8 x 8, current 1920 x 1848, maximum 32767 x 32767
eDP1 connected primary 1366x768+0+1080 (normal left inverted right x axis y axis) 280mm x 160mm
   1366x768      60.11*+
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   680x384       60.00  
   640x360       59.84    59.32    60.00  

DP2-2 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     60.00*+  59.94  
   1680x1050     59.95  
   1280x1024     60.02  
   1280x960      60.00  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x480       60.00    59.94  
   640x480       60.00    59.94  

    $ xrandr --output eDP1 --primary --mode 1366x768 --output DP2-2 --mode 1920x1080  --above eDP1

above used to config when docked

**Comment by ovitor** [comment]
I have the same error, but after undocked and docked again it work like a charm. I noticed that was created another DP-2-3, don't know why..

`DP-2-3 disconnected (normal left inverted right x axis y axis)`

But the hooks doesn't worked yet. Let me know if I could help with some log
