### ISSUE TITLE
Error Writing Config File

### ISSUE THREAD

**Issue by solomon-b** [libthinkpad/dockd#27]
I'm on Arch Linux. I installed from the `AUR` and get an infinite loop of permission denied when trying to config:

```~ λ dockd --config docked
config: error writing config file: Permission denied
config: error writing config file: Permission denied
config: error writing config file: Permission denied
...
```
I tried the patched branch from [this issue](https://github.com/libthinkpad/dockd/issues/9) and it removed the infinite loop, but I still get a `permission denied` error, so I think this is a separate issue.

**Comment by jda** [comment]
Do you have write permissions for `/etc/dockd`? If not, you'll need to run dockd with sudo to write the config files.

**Comment by schoettl** [comment]
I also think that this issue can be closed. The [Arch Wiki article](https://wiki.archlinux.org/index.php/ThinkPad_docks) also states that the command `docd --config docked` must be executed as root, i.e.

```
sudo dockd --config docked
```
