### ISSUE TITLE
Project unmaintained?

### ISSUE THREAD

**Issue by l-e-e-o** [libthinkpad/dockd#28]
As there was no significant activity on the repo or the issues I want to ask the question if this project is dead now? @smclt30p can you give a statement?

**Comment by XenGi** [comment]
no answer in 9 months. Looks pretty dead to me. :/

**Comment by schoettl** [comment]
Hi, I'm the new (co-)maintainer. I don't plan to implement new features for anyone, I only want to help to merge bugfixes and publish releases.

I plan to release the fix for #9 soon on AUR. But don't know how the process for other Linux distros is. Any help is welcome!
