### ISSUE TITLE
Halleluiah

### ISSUE THREAD

**Issue by harmlessdrudge** [libthinkpad/dockd#30]
Pleased to discover this but right now (also pained not to have found it earlier) am wondering whether to futz with it or wait for Linux Mint 19.3, due in 3 weeks or so, just in case it makes the problem go away. 

Am using a Lenovo Thinkpad T440s and being able to dock and undock easily is the main thing I miss about Windows. I see some have not succeeded with this. Would be good to see a list of machines (and distros) that it worked and didn't work with, to save people wasting time. I'll report back later (am using the A02 dock).

Something else I just discovered by chance: Lenovo docking stations have firmware and this can be reflashed. I had no idea.

**Comment by schoettl** [comment]
Nice to hear that. So, it works for you with T440s and A02 dock? Then I would add it to a list in the README.

**Comment by harmlessdrudge** [comment]
I'd forgotten about this, apologies for not reporting back. Turned out I had a faulty docking station (replaced) and my now current Mint 19.3 docks and undocks ok without needing additional software. It doesn't, however, restore the wired network configuration, even when it's manually reset after resuming from sleep. That's the only glitch I have atm. I know that works with Manjaro so I'm hoping it'll get fixed eventually on the deb side of the fence.
