### ISSUE TITLE
Execute external scripts when docking/undocking

### ISSUE THREAD

**Issue by leggettc18** [libthinkpad/dockd#5]
I don't know if there is currently a way to do this currently with dockd, but I thought it would be a good idea to add the ability to execute external scripts when docking or undocking

For example, when docked, perhaps I want to run a bar application of some sort, but when undocked, I want to kill that process and save some screen real estate. Or perhaps I want to turn off wifi when docked and just use ethernet, and then turn it back on when undocking.

Since dockd already does something automatically when docking and undocking I figured it wouldn't be too hard to add some functionality like this in. I may even contribute myself if I can find the time. I just wanted to make sure at least that this isn't considered to be outside the scope of the project or something that someone is already working on or anything like that.

**Comment by smclt30p** [comment]
That's a nice idea, I'll get to it once I get home! :)

**Comment by smclt30p** [comment]
Implemented, feel free to try it out! :)
