### ISSUE TITLE
Ubuntu instructions are not working

### ISSUE THREAD

**Issue by coaxial** [libthinkpad/dockd#6]
Following the instructions for Artful (installin the key, adding to the apt list, and updating) generates an error:

```
W: GPG error: https://thinkpads.org/repo/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 86C3DC31ABD1A026
E: The repository 'http://thinkpads.org/repo/ubuntu artful InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by smclt30p** [comment]
Add the GPG key:

`wget -q -O - http://thinkpads.org/repo/ubuntu/thinkpads.gpg.key | sudo apt-key add -`

**Comment by smclt30p** [comment]
And verify that the key is present:

`apt-key list | grep Ognjen`

**Comment by coaxial** [comment]
Yes, I did, and the key is present.

**Comment by coaxial** [comment]
```
$ apt-key list | grep Ognjen
Warning: apt-key output should not be parsed (stdout is not a terminal)
uid           [ unknown] Ognjen Galic <smclt30p@gmail.com>
```

**Comment by smclt30p** [comment]
Let me boot up a artful vm and see what's going on.

**Comment by smclt30p** [comment]
Can you please verify the signature: 

`6A6B AED7 4C23 4BCA 5371  A79E 86C3 DC31 ABD1 A026`

**Comment by coaxial** [comment]
Yes, I don't know how

**Comment by smclt30p** [comment]
`apt-key list | grep " 86C3 DC31 ABD1 A026"`

**Comment by coaxial** [comment]
Oh I thought you meant the repo's... Nevermind.

It doesn't match:

```
pub   rsa4096 2017-11-16 [SC] [expires: 2027-11-14]
      ACA0 0091 EB32 ACCB 50AA  9DDF B127 FE7A CF3C 0DBA
uid           [ unknown] Ognjen Galic <smclt30p@gmail.com>
sub   rsa4096 2017-11-16 [E] [expires: 2027-11-14]
```

**Comment by smclt30p** [comment]
Add the key again and retry. I was using an old key on the server that got mixed up during migration. Sorry for that.

**Comment by coaxial** [comment]
They keys match now, thank you

**Comment by smclt30p** [comment]
Thank you for reporting.

PS: You ride mountain bikes or road bikes? :)

**Comment by coaxial** [comment]
I use a hybrid, Toronto's roads aren't very smooth.
