### ISSUE TITLE
Daemon not started

### ISSUE THREAD

**Issue by coaxial** [libthinkpad/dockd#7]
I installed `dockd` following the steps, using the thinkpads.org repo.

I logged out and even restarted, but I don't see `dockd --daemon` running.

```
$ ll /etc/dockd/
total 32K
drwxr-xr-x   2 root root 4.0K Mar  4 17:29 .
drwxr-xr-x 192 root root  12K Mar  4 17:36 ..
-rw-r--r--   1 root root  284 Mar  4 17:28 docked.conf
-rwxr-xr-x   1 root root  222 Jan 19 06:35 dock.hook
-rw-r--r--   1 root root  260 Mar  4 17:29 undocked.conf
-rwxr-xr-x   1 root root  224 Jan 19 06:31 undock.hook
```

```
$ ps -ux | grep dockd
coaxial   8759  0.0  0.0  14356  1124 pts/0    S+   17:35   0:00 grep dockd
```

Running i3wm version 4.14.1 on Ubuntu 17.10 on a TP X230

**Comment by smclt30p** [comment]
i3 does not support the XDG Autostart protocol. Add this to your i3 config:

`exec --no-startup-id dockd --daemon`

**Comment by coaxial** [comment]
I can't seem to get it working... With this line in the config file,it launches it twice:

```
coaxial  10460  0.0  0.0   4592   808 ?        S    19:52   0:00 /bin/sh -c dockd --daemon
coaxial  10466  0.0  0.0 141152  3176 ?        Sl   19:52   0:00 dockd --daemon
coaxial  11835  0.0  0.0  14356   928 pts/0    S+   19:53   0:00 grep dockd
```

**Comment by coaxial** [comment]
I also tried running it from the command line when no dockd processes are running, and it doesn't seem to do anything. When I dock or undock, nothing happens.

To clarify, `ps -ux | grep dockd` doesn't show anything, and I start it at the prompt in the foreground.

**Comment by coaxial** [comment]
I use coreboot as my BIOS if that makes any difference.

**Comment by smclt30p** [comment]
Coreboot is not supported. I'm sorry, that's a trade-off of coreboot.

IMO I don't see the appeal of coreboot.

**Comment by schoettl** [comment]
Closing this to clean up issues.
